name: Terraform Apply or Destroy

on:
  workflow_dispatch:

env:
  WORK_DIR: infrastructure
  AWS_REGION: eu-north-1

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORK_DIR }}

      - name: Terraform Action - Apply or Destroy
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORK_DIR }}
